# Generated by Django 5.2.6 on 2026-04-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='join_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('novice', 'Novice'), ('pro', 'Pro'), ('elite', 'Elite')], default='novice', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(blank=True, default='free', max_length=32),
        ),
    ]
