# Generated by Django 6.0.4 on 2026-04-23 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_coach_user_join_code_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='api.program')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('week_number', models.PositiveSmallIntegerField()),
                ('day_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('template_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='api.day')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.workoutplan')),
            ],
            options={
                'ordering': ['scheduled_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('exercise_results', models.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('workout_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_log', to='api.workoutsession')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=140)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.CharField(blank=True, max_length=32)),
                ('load', models.CharField(blank=True, max_length=32)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('intensity', models.CharField(blank=True, max_length=32)),
                ('rest', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('source_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_snapshots', to='api.programexercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_snapshots', to='api.workoutsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['client', 'scheduled_date'], name='api_workout_client__db041c_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['coach', 'status'], name='api_workout_coach_i_9559cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exercisesnapshot',
            unique_together={('workout_session', 'order')},
        ),
    ]
